import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type Section = "math" | "reading_writing";
type Difficulty = "easy" | "medium" | "hard";

interface QuestionSeed {
  section: Section;
  subtype: string;
  difficulty: Difficulty;
  prompt: string;
  explanation: string;
  choices: { label: string; text: string; correct?: true }[];
}

const questions: QuestionSeed[] = [

// ════════════════════════════════════════════════════════════════════════════
// MATH · ALGEBRA  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"If x + 7 = 15, what is x?", explanation:"x = 15 − 7 = 8.",
  choices:[{label:"A",text:"6"},{label:"B",text:"7"},{label:"C",text:"8",correct:true},{label:"D",text:"9"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"What is 3y when y = 4?", explanation:"3 × 4 = 12.",
  choices:[{label:"A",text:"7"},{label:"B",text:"12",correct:true},{label:"C",text:"16"},{label:"D",text:"43"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"Solve: 2x = 18.", explanation:"x = 18 ÷ 2 = 9.",
  choices:[{label:"A",text:"6"},{label:"B",text:"8"},{label:"C",text:"9",correct:true},{label:"D",text:"10"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"If f(x) = 2x + 1, what is f(0)?", explanation:"f(0) = 0 + 1 = 1.",
  choices:[{label:"A",text:"0"},{label:"B",text:"1",correct:true},{label:"C",text:"2"},{label:"D",text:"3"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"Which value of x satisfies x − 5 = 10?", explanation:"x = 10 + 5 = 15.",
  choices:[{label:"A",text:"5"},{label:"B",text:"10"},{label:"C",text:"15",correct:true},{label:"D",text:"50"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"The equation y = 2x + 3 is graphed in the xy-plane. What is the y-intercept?", explanation:"In y = mx + b, b = 3.",
  choices:[{label:"A",text:"2"},{label:"B",text:"3",correct:true},{label:"C",text:"5"},{label:"D",text:"−3"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"What are the solutions to x² − 5x + 6 = 0?", explanation:"(x−2)(x−3) = 0 → x = 2 or x = 3.",
  choices:[{label:"A",text:"x = 1 and x = 6"},{label:"B",text:"x = 2 and x = 3",correct:true},{label:"C",text:"x = −2 and x = −3"},{label:"D",text:"x = 3 and x = 5"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"If 3(x − 2) = 12, what is x?", explanation:"3x − 6 = 12 → 3x = 18 → x = 6.",
  choices:[{label:"A",text:"4"},{label:"B",text:"5"},{label:"C",text:"6",correct:true},{label:"D",text:"8"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"A line passes through (0, 4) and (2, 8). What is its equation?", explanation:"slope = (8−4)/(2−0) = 2; y = 2x + 4.",
  choices:[{label:"A",text:"y = x + 4"},{label:"B",text:"y = 2x + 4",correct:true},{label:"C",text:"y = 2x + 2"},{label:"D",text:"y = 4x + 2"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"What is the value of 2x² when x = 3?", explanation:"2(3²) = 2(9) = 18.",
  choices:[{label:"A",text:"12"},{label:"B",text:"15"},{label:"C",text:"18",correct:true},{label:"D",text:"36"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"Simplify: (x + 3)(x − 3).", explanation:"Difference of squares: x² − 9.",
  choices:[{label:"A",text:"x² + 9"},{label:"B",text:"x² − 9",correct:true},{label:"C",text:"x² − 6x + 9"},{label:"D",text:"x² + 6x − 9"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"If 5 − 2x > 1, which describes the solution?", explanation:"−2x > −4 → x < 2.",
  choices:[{label:"A",text:"x > 2"},{label:"B",text:"x < 2",correct:true},{label:"C",text:"x > −2"},{label:"D",text:"x < −2"}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"A system: 3x + 2y = 12 and x − y = 1. What is x + y?", explanation:"x = y+1 → 5y = 9 → y = 9/5, x = 14/5; x+y = 23/5.",
  choices:[{label:"A",text:"3"},{label:"B",text:"4"},{label:"C",text:"23/5",correct:true},{label:"D",text:"5"}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"If f(x) = x² − 4 and g(x) = 2x + 1, what is f(g(1))?", explanation:"g(1)=3; f(3)=9−4=5.",
  choices:[{label:"A",text:"3"},{label:"B",text:"4"},{label:"C",text:"5",correct:true},{label:"D",text:"6"}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"The roots of ax² + bx + c = 0 sum to 7 and their product is 10. What are the roots?", explanation:"Roots sum to −b/a=7 and product c/a=10 → (x−2)(x−5)=0, roots 2 and 5.",
  choices:[{label:"A",text:"1 and 10"},{label:"B",text:"2 and 5",correct:true},{label:"C",text:"3 and 4"},{label:"D",text:"−2 and −5"}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"If 2^(x+1) = 32, what is x?", explanation:"2^(x+1) = 2^5 → x+1 = 5 → x = 4.",
  choices:[{label:"A",text:"3"},{label:"B",text:"4",correct:true},{label:"C",text:"5"},{label:"D",text:"6"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"What is the slope of the line y = −3x + 7?", explanation:"In y = mx + b, m = −3.",
  choices:[{label:"A",text:"7"},{label:"B",text:"3"},{label:"C",text:"−3",correct:true},{label:"D",text:"−7"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"Evaluate: 4a − b when a = 2 and b = 3.", explanation:"4(2) − 3 = 8 − 3 = 5.",
  choices:[{label:"A",text:"5",correct:true},{label:"B",text:"6"},{label:"C",text:"8"},{label:"D",text:"11"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"Which equation represents a line parallel to y = 3x − 2?", explanation:"Parallel lines share the same slope; only y = 3x + 5 has slope 3.",
  choices:[{label:"A",text:"y = −3x + 1"},{label:"B",text:"y = 3x + 5",correct:true},{label:"C",text:"y = 2x − 3"},{label:"D",text:"y = (1/3)x + 2"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"If |2x − 4| = 6, which are the values of x?", explanation:"2x−4=6 → x=5; 2x−4=−6 → x=−1.",
  choices:[{label:"A",text:"x = 5 only"},{label:"B",text:"x = −1 only"},{label:"C",text:"x = 5 and x = −1",correct:true},{label:"D",text:"x = 1 and x = 5"}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"The function h(t) = −16t² + 64t models the height of a ball in feet. What is the maximum height?", explanation:"t at vertex = −b/(2a) = −64/−32 = 2; h(2) = −16(4)+128 = 64.",
  choices:[{label:"A",text:"32 ft"},{label:"B",text:"48 ft"},{label:"C",text:"64 ft",correct:true},{label:"D",text:"128 ft"}] },
{ section:"math", subtype:"algebra", difficulty:"easy",
  prompt:"Which expression is equivalent to 6x − 2x?", explanation:"6x − 2x = 4x.",
  choices:[{label:"A",text:"4x",correct:true},{label:"B",text:"8x"},{label:"C",text:"4x²"},{label:"D",text:"3x"}] },
{ section:"math", subtype:"algebra", difficulty:"medium",
  prompt:"What value of k makes kx + 3 = 0 have the solution x = −3?", explanation:"k(−3) + 3 = 0 → −3k = −3 → k = 1.",
  choices:[{label:"A",text:"−1"},{label:"B",text:"0"},{label:"C",text:"1",correct:true},{label:"D",text:"3"}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"If log₂(x) = 5, what is x?", explanation:"x = 2⁵ = 32.",
  choices:[{label:"A",text:"10"},{label:"B",text:"16"},{label:"C",text:"25"},{label:"D",text:"32",correct:true}] },
{ section:"math", subtype:"algebra", difficulty:"hard",
  prompt:"Which value satisfies x² − 2x − 8 = 0 and is negative?", explanation:"(x−4)(x+2)=0 → x=4 or x=−2; negative root is −2.",
  choices:[{label:"A",text:"−4"},{label:"B",text:"−2",correct:true},{label:"C",text:"−1"},{label:"D",text:"2"}] },

// ════════════════════════════════════════════════════════════════════════════
// MATH · GEOMETRY  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"A rectangle has length 10 and width 4. What is its area?", explanation:"A = 10 × 4 = 40.",
  choices:[{label:"A",text:"28"},{label:"B",text:"36"},{label:"C",text:"40",correct:true},{label:"D",text:"44"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"What is the perimeter of a square with side length 6?", explanation:"P = 4 × 6 = 24.",
  choices:[{label:"A",text:"12"},{label:"B",text:"18"},{label:"C",text:"24",correct:true},{label:"D",text:"36"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"What is the area of a triangle with base 8 and height 5?", explanation:"A = (1/2)(8)(5) = 20.",
  choices:[{label:"A",text:"13"},{label:"B",text:"20",correct:true},{label:"C",text:"40"},{label:"D",text:"80"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"Two angles of a triangle are 60° and 80°. What is the third angle?", explanation:"180 − 60 − 80 = 40°.",
  choices:[{label:"A",text:"30°"},{label:"B",text:"40°",correct:true},{label:"C",text:"50°"},{label:"D",text:"60°"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"A circle has radius 5. What is its circumference? (Use π ≈ 3.14)", explanation:"C = 2π(5) ≈ 31.4.",
  choices:[{label:"A",text:"15.7"},{label:"B",text:"25"},{label:"C",text:"31.4",correct:true},{label:"D",text:"78.5"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"Line l has slope −2/3 and passes through (6, 1). What is the x-intercept?", explanation:"y−1=−2/3(x−6); set y=0 → x=7.5.",
  choices:[{label:"A",text:"6"},{label:"B",text:"7"},{label:"C",text:"7.5",correct:true},{label:"D",text:"9"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"In a right triangle, legs are 3 and 4. What is the hypotenuse?", explanation:"√(9+16) = √25 = 5.",
  choices:[{label:"A",text:"4"},{label:"B",text:"5",correct:true},{label:"C",text:"6"},{label:"D",text:"7"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"A circle has area 36π. What is its radius?", explanation:"πr² = 36π → r² = 36 → r = 6.",
  choices:[{label:"A",text:"4"},{label:"B",text:"5"},{label:"C",text:"6",correct:true},{label:"D",text:"9"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"What is the volume of a rectangular prism with l=5, w=3, h=2?", explanation:"V = 5×3×2 = 30.",
  choices:[{label:"A",text:"10"},{label:"B",text:"25"},{label:"C",text:"30",correct:true},{label:"D",text:"60"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"Lines m and n are parallel. A transversal creates an angle of 65° with m. What is the co-interior (same-side interior) angle with n?", explanation:"Co-interior angles sum to 180°; 180 − 65 = 115°.",
  choices:[{label:"A",text:"65°"},{label:"B",text:"90°"},{label:"C",text:"115°",correct:true},{label:"D",text:"125°"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"Point A is at (1, 2) and point B is at (4, 6). What is the distance AB?", explanation:"√((4−1)²+(6−2)²) = √(9+16) = 5.",
  choices:[{label:"A",text:"3"},{label:"B",text:"4"},{label:"C",text:"5",correct:true},{label:"D",text:"7"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"What is the midpoint of segment with endpoints (2, 4) and (8, 10)?", explanation:"Midpoint = ((2+8)/2, (4+10)/2) = (5, 7).",
  choices:[{label:"A",text:"(4, 6)"},{label:"B",text:"(5, 7)",correct:true},{label:"C",text:"(6, 8)"},{label:"D",text:"(3, 5)"}] },
{ section:"math", subtype:"geometry", difficulty:"hard",
  prompt:"A cylinder has radius 3 and height 4. What is its volume?", explanation:"V = π(3²)(4) = 36π.",
  choices:[{label:"A",text:"12π"},{label:"B",text:"24π"},{label:"C",text:"36π",correct:true},{label:"D",text:"48π"}] },
{ section:"math", subtype:"geometry", difficulty:"hard",
  prompt:"In triangle ABC, angle A = 30° and angle B = 60°. If side AB = 10, what is side BC?", explanation:"Angle C = 90°; BC is opposite the 30° angle; BC = AB·sin30° = 5.",
  choices:[{label:"A",text:"5",correct:true},{label:"B",text:"5√3"},{label:"C",text:"10"},{label:"D",text:"10√3"}] },
{ section:"math", subtype:"geometry", difficulty:"hard",
  prompt:"A sector of a circle has radius 6 and central angle 90°. What is its area?", explanation:"Area = (90/360)π(6²) = (1/4)(36π) = 9π.",
  choices:[{label:"A",text:"6π"},{label:"B",text:"9π",correct:true},{label:"C",text:"12π"},{label:"D",text:"18π"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"What is the supplement of a 70° angle?", explanation:"180 − 70 = 110°.",
  choices:[{label:"A",text:"20°"},{label:"B",text:"90°"},{label:"C",text:"110°",correct:true},{label:"D",text:"120°"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"A square has area 49. What is its side length?", explanation:"√49 = 7.",
  choices:[{label:"A",text:"6"},{label:"B",text:"7",correct:true},{label:"C",text:"8"},{label:"D",text:"12.25"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"What is the area of a circle with diameter 10?", explanation:"r = 5; A = 25π.",
  choices:[{label:"A",text:"10π"},{label:"B",text:"20π"},{label:"C",text:"25π",correct:true},{label:"D",text:"100π"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"Two similar triangles have sides in ratio 2:3. If the smaller has area 8, what is the area of the larger?", explanation:"Area ratio = (2:3)² = 4:9; larger area = 8×(9/4) = 18.",
  choices:[{label:"A",text:"12"},{label:"B",text:"16"},{label:"C",text:"18",correct:true},{label:"D",text:"24"}] },
{ section:"math", subtype:"geometry", difficulty:"hard",
  prompt:"A cone has radius 4 and height 3. What is its slant height?", explanation:"l = √(r²+h²) = √(16+9) = √25 = 5.",
  choices:[{label:"A",text:"4"},{label:"B",text:"5",correct:true},{label:"C",text:"6"},{label:"D",text:"7"}] },
{ section:"math", subtype:"geometry", difficulty:"hard",
  prompt:"In the coordinate plane, what is the equation of the circle centered at (2, −1) with radius 4?", explanation:"(x−2)² + (y+1)² = 16.",
  choices:[{label:"A",text:"(x+2)² + (y−1)² = 16"},{label:"B",text:"(x−2)² + (y+1)² = 16",correct:true},{label:"C",text:"(x−2)² + (y−1)² = 4"},{label:"D",text:"(x+2)² + (y+1)² = 4"}] },
{ section:"math", subtype:"geometry", difficulty:"easy",
  prompt:"What is the area of a parallelogram with base 9 and height 4?", explanation:"A = 9 × 4 = 36.",
  choices:[{label:"A",text:"13"},{label:"B",text:"26"},{label:"C",text:"36",correct:true},{label:"D",text:"72"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"A right triangle has hypotenuse 13 and one leg 5. What is the other leg?", explanation:"√(13²−5²) = √(169−25) = √144 = 12.",
  choices:[{label:"A",text:"8"},{label:"B",text:"10"},{label:"C",text:"12",correct:true},{label:"D",text:"14"}] },
{ section:"math", subtype:"geometry", difficulty:"hard",
  prompt:"Points A(0,0), B(6,0), and C(3,4) form a triangle. What is the area?", explanation:"Area = (1/2)|base||height| = (1/2)(6)(4) = 12.",
  choices:[{label:"A",text:"9"},{label:"B",text:"12",correct:true},{label:"C",text:"15"},{label:"D",text:"24"}] },
{ section:"math", subtype:"geometry", difficulty:"medium",
  prompt:"An exterior angle of a triangle measures 120°. The two non-adjacent interior angles are equal. What is each?", explanation:"Exterior = sum of two remote interior → each = 60°.",
  choices:[{label:"A",text:"40°"},{label:"B",text:"50°"},{label:"C",text:"60°",correct:true},{label:"D",text:"70°"}] },

// ════════════════════════════════════════════════════════════════════════════
// MATH · PROBABILITY  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"A bag has 3 red and 7 blue marbles. What is P(red)?", explanation:"3/10 = 0.3.",
  choices:[{label:"A",text:"0.2"},{label:"B",text:"0.3",correct:true},{label:"C",text:"0.5"},{label:"D",text:"0.7"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"A fair coin is flipped. What is P(heads)?", explanation:"1/2 = 0.5.",
  choices:[{label:"A",text:"0.25"},{label:"B",text:"0.5",correct:true},{label:"C",text:"0.75"},{label:"D",text:"1"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"A standard die is rolled. What is P(rolling a 4)?", explanation:"1/6.",
  choices:[{label:"A",text:"1/3"},{label:"B",text:"1/4"},{label:"C",text:"1/6",correct:true},{label:"D",text:"1/8"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"A jar has 5 green, 3 yellow, and 2 red candies. What is P(yellow)?", explanation:"3/10 = 0.3.",
  choices:[{label:"A",text:"0.2"},{label:"B",text:"0.3",correct:true},{label:"C",text:"0.5"},{label:"D",text:"0.6"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"From a deck of 52 cards, what is P(drawing an ace)?", explanation:"4/52 = 1/13.",
  choices:[{label:"A",text:"1/4"},{label:"B",text:"1/13",correct:true},{label:"C",text:"1/52"},{label:"D",text:"4/13"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"A fair six-sided die is rolled twice. What is P(6 both times)?", explanation:"(1/6)(1/6) = 1/36.",
  choices:[{label:"A",text:"1/6"},{label:"B",text:"1/12"},{label:"C",text:"1/36",correct:true},{label:"D",text:"1/3"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"A bag has 4 red and 6 blue balls. Two are drawn without replacement. What is P(both red)?", explanation:"(4/10)(3/9) = 12/90 = 2/15.",
  choices:[{label:"A",text:"4/25"},{label:"B",text:"2/15",correct:true},{label:"C",text:"1/5"},{label:"D",text:"1/6"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"Events A and B are independent. P(A) = 0.4 and P(B) = 0.5. What is P(A and B)?", explanation:"0.4 × 0.5 = 0.2.",
  choices:[{label:"A",text:"0.1"},{label:"B",text:"0.2",correct:true},{label:"C",text:"0.45"},{label:"D",text:"0.9"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"What is P(not rolling a 1 on a fair die)?", explanation:"P(not 1) = 1 − 1/6 = 5/6.",
  choices:[{label:"A",text:"1/6"},{label:"B",text:"4/6"},{label:"C",text:"5/6",correct:true},{label:"D",text:"1"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"A student has an 80% chance of passing each of two independent tests. What is the probability of passing both?", explanation:"0.8 × 0.8 = 0.64.",
  choices:[{label:"A",text:"0.16"},{label:"B",text:"0.64",correct:true},{label:"C",text:"0.8"},{label:"D",text:"1.6"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"In a class of 30 students, 12 play soccer and 10 play basketball; 4 play both. What is P(a student plays at least one sport)?", explanation:"(12+10−4)/30 = 18/30 = 0.6.",
  choices:[{label:"A",text:"0.4"},{label:"B",text:"0.5"},{label:"C",text:"0.6",correct:true},{label:"D",text:"0.73"}] },
{ section:"math", subtype:"probability", difficulty:"hard",
  prompt:"A bag has 5 red and 3 green marbles. Three are drawn with replacement. What is P(all red)?", explanation:"(5/8)³ = 125/512.",
  choices:[{label:"A",text:"15/512"},{label:"B",text:"60/512"},{label:"C",text:"125/512",correct:true},{label:"D",text:"125/256"}] },
{ section:"math", subtype:"probability", difficulty:"hard",
  prompt:"A fair coin is flipped 4 times. What is P(exactly 2 heads)?", explanation:"C(4,2)/2⁴ = 6/16 = 3/8.",
  choices:[{label:"A",text:"1/4"},{label:"B",text:"3/8",correct:true},{label:"C",text:"1/2"},{label:"D",text:"3/4"}] },
{ section:"math", subtype:"probability", difficulty:"hard",
  prompt:"P(A) = 0.3, P(B) = 0.4, P(A|B) = 0.2. What is P(A and B)?", explanation:"P(A and B) = P(A|B)·P(B) = 0.2×0.4 = 0.08.",
  choices:[{label:"A",text:"0.06"},{label:"B",text:"0.08",correct:true},{label:"C",text:"0.12"},{label:"D",text:"0.7"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"There are 26 letters in the alphabet. What is P(randomly choosing a vowel)?", explanation:"5 vowels/26 letters.",
  choices:[{label:"A",text:"1/5"},{label:"B",text:"5/26",correct:true},{label:"C",text:"1/4"},{label:"D",text:"5/21"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"A spinner has 4 equal sections colored red, blue, green, and yellow. What is P(not blue)?", explanation:"P = 3/4.",
  choices:[{label:"A",text:"1/4"},{label:"B",text:"1/2"},{label:"C",text:"3/4",correct:true},{label:"D",text:"1"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"A card is drawn from a standard 52-card deck. What is P(red face card)?", explanation:"6 red face cards/52 = 3/26.",
  choices:[{label:"A",text:"1/13"},{label:"B",text:"3/26",correct:true},{label:"C",text:"6/52"},{label:"D",text:"1/4"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"Two dice are rolled. What is P(sum equals 7)?", explanation:"Favorable outcomes: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6; total = 36; P = 1/6.",
  choices:[{label:"A",text:"1/12"},{label:"B",text:"1/6",correct:true},{label:"C",text:"7/36"},{label:"D",text:"1/4"}] },
{ section:"math", subtype:"probability", difficulty:"hard",
  prompt:"A committee of 3 is chosen from 5 men and 4 women. What is P(all women)?", explanation:"C(4,3)/C(9,3) = 4/84 = 1/21.",
  choices:[{label:"A",text:"1/12"},{label:"B",text:"1/21",correct:true},{label:"C",text:"4/9"},{label:"D",text:"1/9"}] },
{ section:"math", subtype:"probability", difficulty:"hard",
  prompt:"From digits 1–9, two are selected without replacement. What is P(both are prime)?", explanation:"Primes: 2,3,5,7 (4 of 9); P = (4/9)(3/8) = 12/72 = 1/6.",
  choices:[{label:"A",text:"4/81"},{label:"B",text:"1/6",correct:true},{label:"C",text:"4/9"},{label:"D",text:"2/9"}] },
{ section:"math", subtype:"probability", difficulty:"easy",
  prompt:"A box has 8 chocolates: 3 dark, 5 milk. What is P(picking milk)?", explanation:"5/8.",
  choices:[{label:"A",text:"3/8"},{label:"B",text:"5/8",correct:true},{label:"C",text:"3/5"},{label:"D",text:"1/2"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"Events A and B are mutually exclusive. P(A) = 0.35 and P(B) = 0.45. What is P(A or B)?", explanation:"P(A or B) = 0.35 + 0.45 = 0.80.",
  choices:[{label:"A",text:"0.45"},{label:"B",text:"0.70"},{label:"C",text:"0.80",correct:true},{label:"D",text:"0.90"}] },
{ section:"math", subtype:"probability", difficulty:"hard",
  prompt:"A test has a 5% false positive rate and a 10% false negative rate. If 1% of the population has the disease, what is P(person has disease | positive test)?", explanation:"Using Bayes: P(D+)=0.01, P(+|D)=0.9, P(+|¬D)=0.05; P(+)=0.01(0.9)+0.99(0.05)=0.0585; P(D|+)=0.009/0.0585≈0.154.",
  choices:[{label:"A",text:"0.05"},{label:"B",text:"0.10"},{label:"C",text:"0.154",correct:true},{label:"D",text:"0.9"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"How many different 3-digit codes can be formed using digits 1–5 if repetition is not allowed?", explanation:"5×4×3 = 60.",
  choices:[{label:"A",text:"10"},{label:"B",text:"15"},{label:"C",text:"60",correct:true},{label:"D",text:"125"}] },
{ section:"math", subtype:"probability", difficulty:"medium",
  prompt:"In how many ways can 4 people be arranged in a line?", explanation:"4! = 24.",
  choices:[{label:"A",text:"8"},{label:"B",text:"12"},{label:"C",text:"16"},{label:"D",text:"24",correct:true}] },

// ════════════════════════════════════════════════════════════════════════════
// MATH · DATA ANALYSIS  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"What is 15% of 200?", explanation:"0.15×200 = 30.",
  choices:[{label:"A",text:"20"},{label:"B",text:"25"},{label:"C",text:"30",correct:true},{label:"D",text:"35"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"The mean of 4, 8, 6, and 10 is?", explanation:"(4+8+6+10)/4 = 28/4 = 7.",
  choices:[{label:"A",text:"6"},{label:"B",text:"7",correct:true},{label:"C",text:"8"},{label:"D",text:"28"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"What is the median of 3, 7, 9, 12, 15?", explanation:"Middle value of sorted set = 9.",
  choices:[{label:"A",text:"7"},{label:"B",text:"9",correct:true},{label:"C",text:"12"},{label:"D",text:"9.2"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"A car travels 180 miles in 3 hours. What is its speed?", explanation:"180/3 = 60 mph.",
  choices:[{label:"A",text:"40 mph"},{label:"B",text:"50 mph"},{label:"C",text:"60 mph",correct:true},{label:"D",text:"90 mph"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"What is the mode of 2, 3, 3, 4, 5, 5, 5?", explanation:"5 appears most often.",
  choices:[{label:"A",text:"2"},{label:"B",text:"3"},{label:"C",text:"4"},{label:"D",text:"5",correct:true}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"A car travels 180 miles in 3 hours. At the same rate, how far in 5 hours?", explanation:"60×5 = 300.",
  choices:[{label:"A",text:"240"},{label:"B",text:"270"},{label:"C",text:"300",correct:true},{label:"D",text:"360"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"A store marks up items 40%. An item costs $50. What is the selling price?", explanation:"50×1.4 = $70.",
  choices:[{label:"A",text:"$60"},{label:"B",text:"$70",correct:true},{label:"C",text:"$75"},{label:"D",text:"$90"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"The range of 4, 9, 2, 15, 7 is?", explanation:"15 − 2 = 13.",
  choices:[{label:"A",text:"7"},{label:"B",text:"11"},{label:"C",text:"13",correct:true},{label:"D",text:"15"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"A set of 5 scores has a mean of 82. Four of the scores are 80, 85, 78, and 90. What is the fifth?", explanation:"Sum = 82×5 = 410; fifth = 410−333 = 77.",
  choices:[{label:"A",text:"75"},{label:"B",text:"77",correct:true},{label:"C",text:"79"},{label:"D",text:"82"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"If 60% of 150 students passed an exam, how many passed?", explanation:"0.6×150 = 90.",
  choices:[{label:"A",text:"60"},{label:"B",text:"75"},{label:"C",text:"90",correct:true},{label:"D",text:"100"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"A scatterplot shows a strong positive correlation. Which r value is most likely?", explanation:"Strong positive → r close to 1.",
  choices:[{label:"A",text:"−0.9"},{label:"B",text:"0.1"},{label:"C",text:"0.5"},{label:"D",text:"0.9",correct:true}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"Population increased from 20,000 to 25,000. What is the % increase?", explanation:"(5000/20000)×100 = 25%.",
  choices:[{label:"A",text:"20%"},{label:"B",text:"25%",correct:true},{label:"C",text:"5%"},{label:"D",text:"30%"}] },
{ section:"math", subtype:"data_analysis", difficulty:"hard",
  prompt:"Data: 2, 4, 4, 4, 5, 5, 7, 9. What is the standard deviation? (Use population formula)", explanation:"Mean=5; deviations²: 9,1,1,1,0,0,4,16; variance=32/8=4; SD=2.",
  choices:[{label:"A",text:"1.5"},{label:"B",text:"2",correct:true},{label:"C",text:"2.5"},{label:"D",text:"4"}] },
{ section:"math", subtype:"data_analysis", difficulty:"hard",
  prompt:"A linear model predicts y = 1.5x + 3. For x = 10, the residual is −2. What is the actual y?", explanation:"Predicted = 1.5(10)+3 = 18; actual = 18+(−2) = 16.",
  choices:[{label:"A",text:"13"},{label:"B",text:"16",correct:true},{label:"C",text:"18"},{label:"D",text:"20"}] },
{ section:"math", subtype:"data_analysis", difficulty:"hard",
  prompt:"A survey has a margin of error of ±3%. If 52% favor a policy, which range is valid?", explanation:"49% to 55%.",
  choices:[{label:"A",text:"49% to 55%",correct:true},{label:"B",text:"50% to 54%"},{label:"C",text:"47% to 57%"},{label:"D",text:"52% only"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"If you earn $12/hr and work 8 hours, how much do you earn?", explanation:"12×8 = $96.",
  choices:[{label:"A",text:"$84"},{label:"B",text:"$90"},{label:"C",text:"$96",correct:true},{label:"D",text:"$104"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"A recipe uses 3 cups of flour for 24 cookies. How many cups for 48 cookies?", explanation:"Double the recipe → 6 cups.",
  choices:[{label:"A",text:"3"},{label:"B",text:"4.5"},{label:"C",text:"6",correct:true},{label:"D",text:"8"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"A graph shows company revenue over 5 years: $2M, $4M, $3M, $6M, $5M. What is the median?", explanation:"Sorted: 2,3,4,5,6; median = $4M.",
  choices:[{label:"A",text:"$3M"},{label:"B",text:"$4M",correct:true},{label:"C",text:"$5M"},{label:"D",text:"$6M"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"Two variables have correlation r = 0.95. What does this indicate?", explanation:"r near 1 indicates a strong positive linear relationship.",
  choices:[{label:"A",text:"No relationship"},{label:"B",text:"Weak negative"},{label:"C",text:"Moderate positive"},{label:"D",text:"Strong positive",correct:true}] },
{ section:"math", subtype:"data_analysis", difficulty:"hard",
  prompt:"A town's population doubles every 10 years. Starting at 5000 in 2000, what is the expected population in 2030?", explanation:"Three doublings: 5000×2³ = 40,000.",
  choices:[{label:"A",text:"15,000"},{label:"B",text:"20,000"},{label:"C",text:"30,000"},{label:"D",text:"40,000",correct:true}] },
{ section:"math", subtype:"data_analysis", difficulty:"hard",
  prompt:"A sample of 100 has mean 68 and SD 10. What % of data falls within one SD? (Empirical rule)", explanation:"By the 68-95-99.7 rule, approximately 68% falls within one SD.",
  choices:[{label:"A",text:"50%"},{label:"B",text:"68%",correct:true},{label:"C",text:"95%"},{label:"D",text:"99.7%"}] },
{ section:"math", subtype:"data_analysis", difficulty:"easy",
  prompt:"A train travels at 60 mph. How long does it take to travel 150 miles?", explanation:"t = 150/60 = 2.5 hours.",
  choices:[{label:"A",text:"2 hours"},{label:"B",text:"2.5 hours",correct:true},{label:"C",text:"3 hours"},{label:"D",text:"3.5 hours"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"Sales data shows a 10% decrease each year from $100,000. What are sales after 2 years?", explanation:"100000×0.9×0.9 = $81,000.",
  choices:[{label:"A",text:"$80,000"},{label:"B",text:"$81,000",correct:true},{label:"C",text:"$82,000"},{label:"D",text:"$90,000"}] },
{ section:"math", subtype:"data_analysis", difficulty:"medium",
  prompt:"A box plot has Q1=10, Q3=20. What is the IQR?", explanation:"IQR = Q3 − Q1 = 10.",
  choices:[{label:"A",text:"5"},{label:"B",text:"10",correct:true},{label:"C",text:"15"},{label:"D",text:"20"}] },
{ section:"math", subtype:"data_analysis", difficulty:"hard",
  prompt:"A study samples 400 people; 60% prefer Brand A. What is the 95% CI assuming SE = 2.4%?", explanation:"CI = 60% ± 1.96(2.4%) ≈ 60% ± 4.7% → (55.3%, 64.7%).",
  choices:[{label:"A",text:"55% to 65%"},{label:"B",text:"55.3% to 64.7%",correct:true},{label:"C",text:"57.6% to 62.4%"},{label:"D",text:"50% to 70%"}] },

// ════════════════════════════════════════════════════════════════════════════
// READING & WRITING · COMPREHENSION  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"The author argues that standardized testing provides a consistent metric for comparison. Which best supports this?", explanation:"A shared scoring scale directly supports consistent comparison.",
  choices:[{label:"A",text:"Testing creates uniform expectations."},{label:"B",text:"A shared scoring scale lets colleges evaluate students equally.",correct:true},{label:"C",text:"High scores correlate with first-year success."},{label:"D",text:"Many students improve with prep."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"According to a passage on climate change, rising sea levels are primarily caused by which two factors?", explanation:"The passage specifically names thermal expansion and melting ice sheets as the two primary causes.",
  choices:[{label:"A",text:"Deforestation and pollution"},{label:"B",text:"Thermal expansion of water and melting ice sheets",correct:true},{label:"C",text:"Ocean currents and tidal patterns"},{label:"D",text:"Rainfall increases and river flooding"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"The main purpose of the passage's first paragraph is to:", explanation:"An introductory paragraph typically establishes the topic and the author's central claim.",
  choices:[{label:"A",text:"Provide a counterargument"},{label:"B",text:"Introduce the topic and central claim",correct:true},{label:"C",text:"Summarize the conclusion"},{label:"D",text:"Cite statistical evidence"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"Which word is closest in meaning to 'meticulous' as used in the passage?", explanation:"Meticulous means very careful and precise.",
  choices:[{label:"A",text:"Careless"},{label:"B",text:"Fast"},{label:"C",text:"Careful and precise",correct:true},{label:"D",text:"Creative"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"Based on context, 'ephemeral' most nearly means:", explanation:"Ephemeral means lasting for a very short time.",
  choices:[{label:"A",text:"Lasting forever"},{label:"B",text:"Very old"},{label:"C",text:"Short-lived",correct:true},{label:"D",text:"Mysterious"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"A student wants to add a transition from causes to effects of deforestation. Which is best?", explanation:"A good transition acknowledges causes while introducing effects.",
  choices:[{label:"A",text:"Deforestation has occurred for centuries."},{label:"B",text:"These causes are only part of the story; the consequences are equally significant.",correct:true},{label:"C",text:"Many governments have enacted policies."},{label:"D",text:"Scientists study the rate of forest loss."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"The passage implies that the scientist's reluctance to publish was due to:", explanation:"The surrounding context suggests fear of professional criticism drove her reluctance.",
  choices:[{label:"A",text:"Lack of funding"},{label:"B",text:"Incomplete data"},{label:"C",text:"Fear of professional criticism",correct:true},{label:"D",text:"Ethical concerns about the experiment"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"Which sentence from the passage best supports the claim that urban planning affects public health?", explanation:"Only the sentence linking green space access to reduced hypertension rates directly supports the claim.",
  choices:[{label:"A",text:"The city council approved new zoning regulations."},{label:"B",text:"Neighborhoods with more green space showed lower rates of hypertension.",correct:true},{label:"C",text:"Urban planners face budget constraints each year."},{label:"D",text:"Residents were surveyed about their daily commutes."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"The author uses the anecdote in paragraph three primarily to:", explanation:"Anecdotes serve to illustrate abstract claims with concrete human examples.",
  choices:[{label:"A",text:"Introduce a counterargument"},{label:"B",text:"Provide statistical evidence"},{label:"C",text:"Illustrate the abstract claim with a concrete example",correct:true},{label:"D",text:"Define a technical term"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"Based on the passage, what can be inferred about the author's opinion of the new policy?", explanation:"Phrases like 'short-sighted' and 'fails to address root causes' signal the author's skepticism.",
  choices:[{label:"A",text:"Strongly supportive"},{label:"B",text:"Neutral and objective"},{label:"C",text:"Skeptical and critical",correct:true},{label:"D",text:"Uncertain but hopeful"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"The word 'bolsters' in the final paragraph most nearly means:", explanation:"Bolsters means to support or strengthen.",
  choices:[{label:"A",text:"Weakens"},{label:"B",text:"Supports",correct:true},{label:"C",text:"Questions"},{label:"D",text:"Replaces"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"What does the passage suggest about the relationship between education and income?", explanation:"The passage presents data showing higher education levels correlate with higher lifetime earnings.",
  choices:[{label:"A",text:"No relationship exists between the two."},{label:"B",text:"Higher education levels correlate with higher lifetime earnings.",correct:true},{label:"C",text:"Income depends primarily on personal connections."},{label:"D",text:"Education reduces income potential."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"hard",
  prompt:"The passage states the policy 'addresses symptoms rather than causes.' Which best captures the implied criticism?", explanation:"The phrase implies the policy is superficial — treating surface issues without resolving underlying problems.",
  choices:[{label:"A",text:"The policy is too expensive."},{label:"B",text:"The policy focuses on surface issues without resolving underlying problems.",correct:true},{label:"C",text:"The policy lacks community input."},{label:"D",text:"The policy duplicates existing regulations."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"hard",
  prompt:"A researcher claims urban green spaces reduce stress. Which, if true, most directly weakens this?", explanation:"If visitors already have lower baseline stress, the green space may not cause the reduction.",
  choices:[{label:"A",text:"City residents report higher stress than rural residents."},{label:"B",text:"Green spaces are in wealthier neighborhoods."},{label:"C",text:"Visitors to green spaces tend to already have lower baseline stress levels.",correct:true},{label:"D",text:"Some residents live far from green spaces."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"hard",
  prompt:"The author's use of the phrase 'deafening silence' in paragraph 5 is best understood as:", explanation:"Deafening silence is an oxymoron used to emphasize the profound and impactful nature of an absence of response.",
  choices:[{label:"A",text:"A literal description of the noise level in the room"},{label:"B",text:"An oxymoron emphasizing the profound impact of no response",correct:true},{label:"C",text:"A reference to hearing impairment"},{label:"D",text:"A neutral observation about the meeting"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"The primary purpose of the concluding paragraph is to:", explanation:"Concluding paragraphs typically restate the main argument and call the reader to action or reflection.",
  choices:[{label:"A",text:"Introduce new evidence"},{label:"B",text:"Restate the main argument and suggest implications",correct:true},{label:"C",text:"Provide a counterpoint"},{label:"D",text:"Define key terms"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"Which sentence most effectively introduces the following paragraph about the long-term effects of sleep deprivation?", explanation:"A topic sentence should directly introduce what follows — long-term effects — without detailing results already covered.",
  choices:[{label:"A",text:"Many teenagers do not get enough sleep on school nights."},{label:"B",text:"While the immediate effects of sleep deprivation are well-known, its long-term consequences deserve closer attention.",correct:true},{label:"C",text:"Caffeine is commonly used to counteract sleepiness."},{label:"D",text:"Sleep research has expanded rapidly in recent decades."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"hard",
  prompt:"The author shifts from describing historical events to analyzing their modern relevance. What structural technique achieves this?", explanation:"Moving from narrative to analysis is a shift from expository description to argumentative commentary.",
  choices:[{label:"A",text:"Flashback"},{label:"B",text:"Foreshadowing"},{label:"C",text:"Transition from expository narrative to analytical commentary",correct:true},{label:"D",text:"In medias res"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"Which choice best explains why the author includes the quotation from Dr. Singh?", explanation:"Expert quotes are typically included to add credibility and provide specific support for the author's claim.",
  choices:[{label:"A",text:"To introduce a counterargument"},{label:"B",text:"To add credibility and specific support for the author's claim",correct:true},{label:"C",text:"To entertain the reader"},{label:"D",text:"To define technical vocabulary"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"According to the passage, which factor most contributed to the industrial revolution?", explanation:"The passage directly states that access to coal and iron resources was the foundational factor.",
  choices:[{label:"A",text:"Colonial expansion"},{label:"B",text:"Democratic governance"},{label:"C",text:"Access to coal and iron resources",correct:true},{label:"D",text:"Agricultural surplus"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"The chart accompanying the passage shows a steady rise in renewable energy use from 2010 to 2020. Which claim does the chart best support?", explanation:"A steady upward trend directly supports the claim that adoption has been increasing.",
  choices:[{label:"A",text:"Fossil fuel use has declined."},{label:"B",text:"Renewable energy adoption has been increasing steadily.",correct:true},{label:"C",text:"Energy costs have decreased."},{label:"D",text:"Government subsidies caused the growth."}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"hard",
  prompt:"The author contrasts two economists' views in paragraph 4. What is the primary purpose of this contrast?", explanation:"Presenting opposing views strengthens the argument by acknowledging complexity before taking a position.",
  choices:[{label:"A",text:"To show the author is undecided"},{label:"B",text:"To entertain with an academic debate"},{label:"C",text:"To acknowledge complexity and strengthen the argument by taking a position",correct:true},{label:"D",text:"To summarize the history of economic thought"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"easy",
  prompt:"What does the author mean by 'the tide is turning' in paragraph 2?", explanation:"'The tide is turning' is an idiom meaning that prevailing opinions or conditions are beginning to change.",
  choices:[{label:"A",text:"Ocean tides affect the local ecosystem"},{label:"B",text:"Prevailing opinions or conditions are starting to change",correct:true},{label:"C",text:"The situation is getting worse"},{label:"D",text:"Scientists are studying ocean levels"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"medium",
  prompt:"Which evidence would most effectively strengthen the author's argument that remote work increases productivity?", explanation:"Direct productivity measurements of the same workers before and after a policy change provide the strongest causal evidence.",
  choices:[{label:"A",text:"A survey of workers who prefer working from home"},{label:"B",text:"A comparison of output levels before and after a remote work policy was implemented",correct:true},{label:"C",text:"Statistics on commute times in major cities"},{label:"D",text:"An interview with a CEO who supports flexible work"}] },
{ section:"reading_writing", subtype:"comprehension", difficulty:"hard",
  prompt:"The author acknowledges a limitation of the study in paragraph 6 in order to:", explanation:"Acknowledging limitations builds the author's credibility and demonstrates academic integrity.",
  choices:[{label:"A",text:"Undermine confidence in the conclusion"},{label:"B",text:"Introduce a new hypothesis"},{label:"C",text:"Build credibility by demonstrating awareness of the study's scope",correct:true},{label:"D",text:"Compare with a rival study"}] },

// ════════════════════════════════════════════════════════════════════════════
// READING & WRITING · GRAMMAR  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which of the following correctly uses a comma?", explanation:"A comma goes before a coordinating conjunction joining two independent clauses.",
  choices:[{label:"A",text:"She studied hard, but, she still felt unprepared."},{label:"B",text:"She studied hard, but she still felt unprepared.",correct:true},{label:"C",text:"She studied hard but, she still felt unprepared."},{label:"D",text:"She studied hard but she still felt unprepared."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which sentence uses the apostrophe correctly?", explanation:"Possessive singular: student's notebook.",
  choices:[{label:"A",text:"The students notebook was left on the desk."},{label:"B",text:"The student's notebook was left on the desk.",correct:true},{label:"C",text:"The students' notebook was left on the desk."},{label:"D",text:"The student's' notebook was left on the desk."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which sentence is grammatically correct?", explanation:"Subject-verb agreement: 'each' is singular and takes 'was.'",
  choices:[{label:"A",text:"Each of the students were given a textbook."},{label:"B",text:"Each of the students was given a textbook.",correct:true},{label:"C",text:"Each of the students are given a textbook."},{label:"D",text:"Each of the student was given a textbook."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which correctly uses a semicolon?", explanation:"A semicolon joins two independent clauses without a conjunction.",
  choices:[{label:"A",text:"She loves hiking; but she hates camping."},{label:"B",text:"She loves hiking; she hates camping.",correct:true},{label:"C",text:"She loves hiking, she hates camping."},{label:"D",text:"She loves hiking: she hates camping."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which version avoids a dangling modifier?", explanation:"The modifier must directly precede the noun it describes.",
  choices:[{label:"A",text:"Running quickly, the bus was missed by Jan."},{label:"B",text:"Running quickly, Jan missed the bus.",correct:true},{label:"C",text:"The bus was missed by Jan, who ran quickly."},{label:"D",text:"Running quickly was Jan, who missed the bus."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which effectively combines: 'The report was thorough. It was clearly written.'", explanation:"'Not only…but also' combines two parallel attributes effectively.",
  choices:[{label:"A",text:"The report was thorough and it was clearly written too."},{label:"B",text:"The report was not only thorough but also clearly written.",correct:true},{label:"C",text:"Being thorough, the report was clearly written."},{label:"D",text:"The report, thorough, was clearly written."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which is the correct pronoun in: 'The award was given to Maria and ___ '?", explanation:"After a preposition ('to'), use the objective pronoun 'me.'",
  choices:[{label:"A",text:"I"},{label:"B",text:"me",correct:true},{label:"C",text:"myself"},{label:"D",text:"we"}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which is the most concise version? 'Due to the fact that it was raining, the game was cancelled.'", explanation:"'Because it was raining' is more concise than 'due to the fact that.'",
  choices:[{label:"A",text:"Due to the fact that it was raining, the game was cancelled."},{label:"B",text:"Because it was raining, the game was cancelled.",correct:true},{label:"C",text:"Owing to the precipitation, the game was cancelled."},{label:"D",text:"The game was cancelled, this being because of rain."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Identify the sentence with correct subject-verb agreement:", explanation:"'Neither' takes a singular verb.",
  choices:[{label:"A",text:"Neither of the answers are correct."},{label:"B",text:"Neither of the answers is correct.",correct:true},{label:"C",text:"Neither answers is correct."},{label:"D",text:"Neither the answer are correct."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which correctly uses the colon?", explanation:"A colon introduces a list or explanation that follows an independent clause.",
  choices:[{label:"A",text:"She needed: eggs, milk, and butter."},{label:"B",text:"She needed the following items: eggs, milk, and butter.",correct:true},{label:"C",text:"She needed eggs: milk and butter."},{label:"D",text:"She needed eggs, milk: and butter."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which is the correct form? 'The data ___ inconclusive.'", explanation:"'Data' is technically plural; 'are' is correct in formal usage.",
  choices:[{label:"A",text:"was"},{label:"B",text:"are",correct:true},{label:"C",text:"is"},{label:"D",text:"were not"}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which sentence correctly uses the past perfect tense?", explanation:"Past perfect (had + past participle) expresses action completed before another past action.",
  choices:[{label:"A",text:"She finished her homework when he called."},{label:"B",text:"She had finished her homework when he called.",correct:true},{label:"C",text:"She was finishing her homework when he called."},{label:"D",text:"She has finished her homework when he called."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"hard",
  prompt:"Which correctly uses 'who' vs. 'whom'? 'The manager ___ you recommended was promoted.'", explanation:"'Whom' is the object of 'recommended'; you recommended whom.",
  choices:[{label:"A",text:"who"},{label:"B",text:"whom",correct:true},{label:"C",text:"whoever"},{label:"D",text:"whomever"}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"hard",
  prompt:"Which version of the sentence is parallel in structure? 'She likes hiking, to swim, and running.'", explanation:"All gerunds make the structure parallel.",
  choices:[{label:"A",text:"She likes hiking, to swim, and running."},{label:"B",text:"She likes hiking, swimming, and running.",correct:true},{label:"C",text:"She likes to hike, swim, and running."},{label:"D",text:"She likes hiking, swimming, and to run."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"hard",
  prompt:"Which sentence correctly uses a restrictive clause?", explanation:"A restrictive clause ('that') identifies which item; no commas needed.",
  choices:[{label:"A",text:"The book, that I borrowed, was excellent."},{label:"B",text:"The book that I borrowed was excellent.",correct:true},{label:"C",text:"The book which, I borrowed, was excellent."},{label:"D",text:"The book, which I borrowed was excellent."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which uses 'its' vs. 'it's' correctly?", explanation:"'It's' = it is; 'its' = belonging to it.",
  choices:[{label:"A",text:"The dog wagged it's tail."},{label:"B",text:"The dog wagged its tail.",correct:true},{label:"C",text:"The dog wagged its' tail."},{label:"D",text:"The dog wagged its tail its happy."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which uses 'there/their/they're' correctly?", explanation:"'They're' = they are; 'their' = belonging to them; 'there' = that place.",
  choices:[{label:"A",text:"Their going to there house over their."},{label:"B",text:"They're going to their house over there.",correct:true},{label:"C",text:"There going to they're house over their."},{label:"D",text:"Their going to their house over they're."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which sentence has an unnecessary comma?", explanation:"Do not use a comma between a subject and its verb.",
  choices:[{label:"A",text:"The teacher, who was late, apologized to the class."},{label:"B",text:"The old oak tree, which had stood for 200 years, finally fell."},{label:"C",text:"The students, studied hard for the exam.",correct:true},{label:"D",text:"After the rain, the streets were slippery."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which correctly places the adverb 'only'? (The intended meaning: she saw only him.)", explanation:"'Only' must be placed directly before the word it modifies.",
  choices:[{label:"A",text:"She only saw him at the party."},{label:"B",text:"Only she saw him at the party."},{label:"C",text:"She saw only him at the party.",correct:true},{label:"D",text:"She saw him only at the party."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"hard",
  prompt:"Which correctly uses the subjunctive mood?", explanation:"The subjunctive expresses hypothetical conditions: 'If I were' not 'was.'",
  choices:[{label:"A",text:"If I was taller, I could reach the shelf."},{label:"B",text:"If I were taller, I could reach the shelf.",correct:true},{label:"C",text:"If I am taller, I could reach the shelf."},{label:"D",text:"If I be taller, I could reach the shelf."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"hard",
  prompt:"Which version correctly uses an em dash?", explanation:"An em dash sets off a parenthetical element for emphasis.",
  choices:[{label:"A",text:"The solution - though risky - was the only option."},{label:"B",text:"The solution—though risky—was the only option.",correct:true},{label:"C",text:"The solution, though risky, was the only option."},{label:"D",text:"The solution (though risky) was the only option."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"easy",
  prompt:"Which sentence uses 'fewer' vs. 'less' correctly?", explanation:"Use 'fewer' for countable nouns; 'less' for uncountable.",
  choices:[{label:"A",text:"There are less students today."},{label:"B",text:"There are fewer students today.",correct:true},{label:"C",text:"There are fewer water in the glass."},{label:"D",text:"There is fewer books on the shelf."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which sentence avoids a comma splice?", explanation:"A comma alone cannot join two independent clauses; use a semicolon or conjunction.",
  choices:[{label:"A",text:"It was late, we decided to leave."},{label:"B",text:"It was late; we decided to leave.",correct:true},{label:"C",text:"It was late, however, we decided to leave."},{label:"D",text:"It was late we decided to leave."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"hard",
  prompt:"Which correctly uses the present perfect progressive?", explanation:"Present perfect progressive: has/have + been + verb-ing.",
  choices:[{label:"A",text:"She studied medicine for six years."},{label:"B",text:"She has studied medicine for six years."},{label:"C",text:"She has been studying medicine for six years.",correct:true},{label:"D",text:"She had been studying medicine for six years."}] },
{ section:"reading_writing", subtype:"grammar", difficulty:"medium",
  prompt:"Which correctly punctuates the list? 'I need to buy apples oranges and bananas.'", explanation:"Use commas to separate items in a list.",
  choices:[{label:"A",text:"I need to buy apples; oranges; and bananas."},{label:"B",text:"I need to buy apples, oranges, and bananas.",correct:true},{label:"C",text:"I need to buy: apples, oranges and bananas."},{label:"D",text:"I need to buy apples, oranges and, bananas."}] },

// ════════════════════════════════════════════════════════════════════════════
// READING & WRITING · VOCABULARY  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The scientist's findings were _______ by her peers, who praised the rigor of her methodology.", explanation:"'Validated' = confirmed, fitting praise for rigorous work.",
  choices:[{label:"A",text:"ignored"},{label:"B",text:"validated",correct:true},{label:"C",text:"disputed"},{label:"D",text:"misrepresented"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'benevolent' most nearly means:", explanation:"Benevolent = kind and generous.",
  choices:[{label:"A",text:"strict"},{label:"B",text:"cautious"},{label:"C",text:"kind and generous",correct:true},{label:"D",text:"indifferent"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'ambiguous' most nearly means:", explanation:"Ambiguous = open to more than one interpretation.",
  choices:[{label:"A",text:"clear and direct"},{label:"B",text:"open to multiple interpretations",correct:true},{label:"C",text:"offensive"},{label:"D",text:"exciting"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'diligent' most nearly means:", explanation:"Diligent = hardworking and careful.",
  choices:[{label:"A",text:"lazy"},{label:"B",text:"smart"},{label:"C",text:"hardworking",correct:true},{label:"D",text:"creative"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'condone' most nearly means:", explanation:"Condone = to accept or allow behavior that is considered wrong.",
  choices:[{label:"A",text:"punish"},{label:"B",text:"celebrate"},{label:"C",text:"overlook or accept",correct:true},{label:"D",text:"prevent"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"As used in the passage, 'tenacious' most nearly means:", explanation:"Tenacious = persistent and determined.",
  choices:[{label:"A",text:"flexible"},{label:"B",text:"persistent and determined",correct:true},{label:"C",text:"fragile"},{label:"D",text:"gentle"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The professor's lecture was _______, covering topics from ancient history to modern philosophy without a clear focus.", explanation:"Discursive = tending to wander from subject to subject.",
  choices:[{label:"A",text:"concise"},{label:"B",text:"discursive",correct:true},{label:"C",text:"technical"},{label:"D",text:"inspiring"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The politician gave a _______ speech that carefully avoided taking any definitive position.", explanation:"Equivocal = using ambiguous language to avoid commitment.",
  choices:[{label:"A",text:"forthright"},{label:"B",text:"passionate"},{label:"C",text:"equivocal",correct:true},{label:"D",text:"brief"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The artist's _______ approach combined classical technique with abstract expression.", explanation:"Eclectic = deriving ideas from a broad range of sources.",
  choices:[{label:"A",text:"rigid"},{label:"B",text:"traditional"},{label:"C",text:"eclectic",correct:true},{label:"D",text:"simplistic"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The critic described the novel as _______, meaning it had multiple layers of meaning.", explanation:"Nuanced = characterized by subtle distinctions.",
  choices:[{label:"A",text:"simplistic"},{label:"B",text:"nuanced",correct:true},{label:"C",text:"verbose"},{label:"D",text:"sensational"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"Her _______ response surprised everyone; she usually spoke her mind directly.", explanation:"Circumspect = wary and unwilling to take risks; careful.",
  choices:[{label:"A",text:"blunt"},{label:"B",text:"enthusiastic"},{label:"C",text:"circumspect",correct:true},{label:"D",text:"hostile"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The new CEO was known for her _______ leadership style, empowering employees to make decisions.", explanation:"Autonomy-focused leadership is described as delegating; 'decentralized' or 'laissez-faire' apply, but 'delegate-oriented' best fits.",
  choices:[{label:"A",text:"authoritarian"},{label:"B",text:"micromanaging"},{label:"C",text:"delegative",correct:true},{label:"D",text:"bureaucratic"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"hard",
  prompt:"The historian described the emperor's rule as _______ — oppressive on the surface yet surprisingly tolerant of dissent.", explanation:"Paradoxical = seemingly contradictory but nonetheless true.",
  choices:[{label:"A",text:"systematic"},{label:"B",text:"paradoxical",correct:true},{label:"C",text:"authoritative"},{label:"D",text:"predictable"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"hard",
  prompt:"Her _______ remarks during the debate belittled her opponent without offering any substantive policy arguments.", explanation:"Disparaging = expressing the opinion that something is of little worth; contemptuous.",
  choices:[{label:"A",text:"complimentary"},{label:"B",text:"analytical"},{label:"C",text:"disparaging",correct:true},{label:"D",text:"philosophical"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"hard",
  prompt:"The scientist's findings were considered _______ because they could not be replicated by other researchers.", explanation:"Spurious = false or fake, especially when appearing true.",
  choices:[{label:"A",text:"groundbreaking"},{label:"B",text:"reproducible"},{label:"C",text:"spurious",correct:true},{label:"D",text:"exhaustive"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'audacious' most nearly means:", explanation:"Audacious = showing a willingness to take bold risks.",
  choices:[{label:"A",text:"timid"},{label:"B",text:"bold and daring",correct:true},{label:"C",text:"quiet"},{label:"D",text:"forgetful"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'opaque' most nearly means:", explanation:"Opaque = not clear or transparent; hard to understand.",
  choices:[{label:"A",text:"transparent"},{label:"B",text:"colorful"},{label:"C",text:"not clear or transparent",correct:true},{label:"D",text:"bright"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The students found the professor _______, as she always supported and encouraged their academic growth.", explanation:"Nurturing = encouraging growth and development.",
  choices:[{label:"A",text:"demanding"},{label:"B",text:"indifferent"},{label:"C",text:"nurturing",correct:true},{label:"D",text:"distant"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"Which word best replaces 'said' to convey forceful assertion? 'He _______ that the proposal was fundamentally flawed.'", explanation:"Asserted implies a forceful, confident statement.",
  choices:[{label:"A",text:"whispered"},{label:"B",text:"mentioned"},{label:"C",text:"asserted",correct:true},{label:"D",text:"asked"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"hard",
  prompt:"The philosopher's argument was considered _______ because it assumed as true the very point it was trying to prove.", explanation:"Circular reasoning = begging the question; using a conclusion as a premise.",
  choices:[{label:"A",text:"deductive"},{label:"B",text:"circular",correct:true},{label:"C",text:"inductive"},{label:"D",text:"empirical"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"hard",
  prompt:"The ambassador's tone was _______ — formally pleasant but masking deep displeasure.", explanation:"Diplomatic language can be cordial while concealing underlying tension; 'unctuous' or 'diplomatic' fit, but 'diplomatic' captures both pleasant and strategic qualities.",
  choices:[{label:"A",text:"hostile"},{label:"B",text:"diplomatic",correct:true},{label:"C",text:"candid"},{label:"D",text:"abrasive"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"easy",
  prompt:"The word 'obsolete' most nearly means:", explanation:"Obsolete = no longer produced or used; out of date.",
  choices:[{label:"A",text:"brand new"},{label:"B",text:"essential"},{label:"C",text:"out of date",correct:true},{label:"D",text:"valuable"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The word 'pragmatic' most nearly means:", explanation:"Pragmatic = dealing with things sensibly and practically.",
  choices:[{label:"A",text:"idealistic"},{label:"B",text:"impulsive"},{label:"C",text:"practical and sensible",correct:true},{label:"D",text:"emotional"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"hard",
  prompt:"The text describes the scientist's work as 'seminal.' What does this mean in context?", explanation:"Seminal = strongly influencing later developments; foundational.",
  choices:[{label:"A",text:"Recently published"},{label:"B",text:"Widely criticized"},{label:"C",text:"Foundational and highly influential",correct:true},{label:"D",text:"Preliminary and incomplete"}] },
{ section:"reading_writing", subtype:"vocabulary", difficulty:"medium",
  prompt:"The word 'alleviate' most nearly means:", explanation:"Alleviate = to make suffering or a problem less severe.",
  choices:[{label:"A",text:"worsen"},{label:"B",text:"ignore"},{label:"C",text:"lessen or relieve",correct:true},{label:"D",text:"cure completely"}] },

// ════════════════════════════════════════════════════════════════════════════
// READING & WRITING · RHETORIC  (25 questions)
// ════════════════════════════════════════════════════════════════════════════
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The author's tone in describing the committee's decision can best be described as:", explanation:"Words like 'hasty' and 'predictable failure' signal criticism.",
  choices:[{label:"A",text:"celebratory"},{label:"B",text:"neutral"},{label:"C",text:"critical",correct:true},{label:"D",text:"nostalgic"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"A researcher claims urban green spaces reduce stress. Which most directly weakens this?", explanation:"Pre-existing lower baseline stress is a confounding variable.",
  choices:[{label:"A",text:"City residents report higher stress overall."},{label:"B",text:"Green spaces are in wealthier areas."},{label:"C",text:"Visitors already have lower baseline stress levels.",correct:true},{label:"D",text:"Some residents live far from green spaces."}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"easy",
  prompt:"The author opens with a vivid anecdote about a flood survivor. This rhetorical strategy is intended to:", explanation:"Personal anecdotes at the opening engage reader emotion and illustrate the issue concretely.",
  choices:[{label:"A",text:"Provide statistical support for a claim"},{label:"B",text:"Engage the reader emotionally and illustrate the issue",correct:true},{label:"C",text:"Define a technical term"},{label:"D",text:"Introduce a counterargument"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"easy",
  prompt:"Which type of appeal does the following sentence use? 'Nine out of ten doctors recommend this treatment.'", explanation:"Appealing to expert authority is a logos/ethos appeal — specifically ethos through credibility.",
  choices:[{label:"A",text:"Pathos (emotional appeal)"},{label:"B",text:"Ethos (appeal to credibility)",correct:true},{label:"C",text:"Kairos (appeal to timing)"},{label:"D",text:"Logos (logical evidence)"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"easy",
  prompt:"The phrase 'the clock is ticking' is an example of:", explanation:"'The clock is ticking' uses urgency language — metaphor and kairos.",
  choices:[{label:"A",text:"A simile"},{label:"B",text:"A metaphor",correct:true},{label:"C",text:"Alliteration"},{label:"D",text:"Hyperbole"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The author ends each paragraph with a rhetorical question. The primary effect of this technique is:", explanation:"Rhetorical questions prompt the reader to reflect without requiring an explicit answer.",
  choices:[{label:"A",text:"To provide definitive answers"},{label:"B",text:"To prompt the reader to reflect on the issue",correct:true},{label:"C",text:"To introduce new evidence"},{label:"D",text:"To acknowledge a counterargument"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The author uses the phrase 'wolves in sheep's clothing' to describe the policy makers. This is an example of:", explanation:"'Wolves in sheep's clothing' is an allusion to a well-known fable, used metaphorically.",
  choices:[{label:"A",text:"Personification"},{label:"B",text:"Allusion",correct:true},{label:"C",text:"Understatement"},{label:"D",text:"Hyperbole"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"Which choice would most effectively conclude the argument that technology has improved education?", explanation:"A conclusion should echo the thesis and leave the reader with the strongest case for the author's position.",
  choices:[{label:"A",text:"Technology is not without its drawbacks."},{label:"B",text:"Therefore, with thoughtful integration, technology remains one of the most powerful tools educators have ever had.",correct:true},{label:"C",text:"Many students still prefer traditional textbooks."},{label:"D",text:"Further research on this topic is needed."}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The repetition of 'We shall fight' throughout the speech is an example of:", explanation:"Anaphora is the repetition of a word or phrase at the beginning of successive clauses.",
  choices:[{label:"A",text:"Alliteration"},{label:"B",text:"Anaphora",correct:true},{label:"C",text:"Assonance"},{label:"D",text:"Chiasmus"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"When the author writes 'the market crashed with a thunderous roar,' the crash is described using:", explanation:"Giving human or sensory qualities to abstract events is personification; a thunderous roar attributes sound to an economic event.",
  choices:[{label:"A",text:"Understatement"},{label:"B",text:"Simile"},{label:"C",text:"Personification",correct:true},{label:"D",text:"Paradox"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The author includes a counterargument in paragraph 4 primarily to:", explanation:"Addressing counterarguments builds credibility by showing fairness and then refuting them.",
  choices:[{label:"A",text:"Agree with the opposing position"},{label:"B",text:"Confuse the reader"},{label:"C",text:"Build credibility by addressing and refuting objections",correct:true},{label:"D",text:"Shift the focus of the essay"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"The author's use of irony in describing the 'peaceful bombardment' is best understood as:", explanation:"Describing bombardment as peaceful is ironic — the contrast highlights the horror of war by understating it.",
  choices:[{label:"A",text:"A sincere description of a gentle military operation"},{label:"B",text:"Irony that highlights the contradiction between language and reality",correct:true},{label:"C",text:"A metaphor for diplomatic negotiations"},{label:"D",text:"An example of hyperbole"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"The passage begins with logos, then transitions to pathos. What is the likely rhetorical purpose of this shift?", explanation:"Starting with logic establishes credibility; shifting to emotion mobilizes the reader to act.",
  choices:[{label:"A",text:"To confuse the reader"},{label:"B",text:"To establish credibility before motivating the reader emotionally",correct:true},{label:"C",text:"To weaken the argument's logical foundation"},{label:"D",text:"To avoid taking a clear position"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"Which of the following is the most effective revision of this weak thesis: 'Social media has pros and cons.'?", explanation:"A strong thesis takes a specific, arguable position rather than stating an obvious observation.",
  choices:[{label:"A",text:"Social media is used by millions of people worldwide."},{label:"B",text:"Social media affects people in different ways."},{label:"C",text:"While social media facilitates connection, its promotion of comparison culture significantly harms adolescent mental health.",correct:true},{label:"D",text:"Social media is good for some people but bad for others."}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"The author uses tricolon in the phrase 'We came, we saw, we conquered.' The primary effect is:", explanation:"Tricolon (three parallel clauses) creates rhythm and emphasizes the completeness or inevitability of the action.",
  choices:[{label:"A",text:"To create ambiguity"},{label:"B",text:"To create rhythm and emphasize completeness of action",correct:true},{label:"C",text:"To introduce a counterargument"},{label:"D",text:"To define key terms"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"easy",
  prompt:"Which type of appeal is used in: 'Think of the children who suffer every day without clean water.'", explanation:"Appealing to emotion (pathos) by invoking the suffering of children.",
  choices:[{label:"A",text:"Logos"},{label:"B",text:"Ethos"},{label:"C",text:"Pathos",correct:true},{label:"D",text:"Kairos"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"easy",
  prompt:"The statement 'This is the most important election of our lifetime' is an example of:", explanation:"Hyperbole = exaggeration used for emphasis or effect.",
  choices:[{label:"A",text:"Understatement"},{label:"B",text:"Metaphor"},{label:"C",text:"Hyperbole",correct:true},{label:"D",text:"Personification"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The author describes two competing solutions without committing to either. This rhetorical stance is known as:", explanation:"Presenting both sides without taking a position is called false balance or presenting a balanced view; in argument, it may be called equivocation.",
  choices:[{label:"A",text:"Straw man"},{label:"B",text:"False balance",correct:true},{label:"C",text:"Ad hominem"},{label:"D",text:"Red herring"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"Which revision most effectively strengthens the argument's call to action?", explanation:"Strong calls to action use direct, imperative language and connect the action to the stakes.",
  choices:[{label:"A",text:"One might consider perhaps signing the petition if possible."},{label:"B",text:"It would be nice if people signed the petition."},{label:"C",text:"Sign the petition today — every signature brings us closer to clean water for all.",correct:true},{label:"D",text:"People can sign the petition if they want."}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"The author's argument relies on a slippery slope fallacy. Which of the following best describes this?", explanation:"A slippery slope assumes one event will inevitably lead to extreme consequences without proof.",
  choices:[{label:"A",text:"The author assumes the audience already agrees with the conclusion."},{label:"B",text:"The author argues that one event will inevitably lead to extreme consequences without sufficient evidence.",correct:true},{label:"C",text:"The author attacks the opponent personally."},{label:"D",text:"The author presents a false choice between two options."}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"The passage uses an extended metaphor comparing the economy to a 'patient recovering from surgery.' What is the effect of this?", explanation:"Extended metaphors allow readers to understand complex abstract systems through familiar, concrete experience.",
  choices:[{label:"A",text:"It trivializes the seriousness of economic issues."},{label:"B",text:"It makes the abstract economic situation concrete and emotionally accessible.",correct:true},{label:"C",text:"It introduces a logical fallacy."},{label:"D",text:"It shifts the essay from persuasion to narrative."}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"easy",
  prompt:"'Bittersweet' is an example of:", explanation:"An oxymoron combines contradictory terms.",
  choices:[{label:"A",text:"Simile"},{label:"B",text:"Metaphor"},{label:"C",text:"Oxymoron",correct:true},{label:"D",text:"Alliteration"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The phrase 'the pot calling the kettle black' is an example of:", explanation:"This is a well-known idiom also used as an allusion to highlight hypocrisy.",
  choices:[{label:"A",text:"Metaphor"},{label:"B",text:"Hyperbole"},{label:"C",text:"Idiom",correct:true},{label:"D",text:"Understatement"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"hard",
  prompt:"Which of the following best describes an ad hominem argument?", explanation:"Ad hominem attacks the person making the argument rather than the argument itself.",
  choices:[{label:"A",text:"Using emotion rather than logic to persuade"},{label:"B",text:"Attacking the person making the argument rather than the argument itself",correct:true},{label:"C",text:"Appealing to a false authority"},{label:"D",text:"Presenting an oversimplified choice"}] },
{ section:"reading_writing", subtype:"rhetoric", difficulty:"medium",
  prompt:"The author's decision to use second-person ('you') throughout the essay most likely serves to:", explanation:"Second person creates direct engagement, making the reader feel personally addressed and responsible.",
  choices:[{label:"A",text:"Distance the reader from the topic"},{label:"B",text:"Create a formal, academic tone"},{label:"C",text:"Directly engage the reader and create a sense of personal responsibility",correct:true},{label:"D",text:"Avoid taking a personal stance"}] },

]; // end questions array

async function main() {
  console.log(`Seeding ${questions.length} questions…`);

  await prisma.sessionAnswer.deleteMany();
  await prisma.score.deleteMany();
  await prisma.testSession.deleteMany();
  await prisma.choice.deleteMany();
  await prisma.question.deleteMany();

  for (const q of questions) {
    const correctIndex = q.choices.findIndex(c => c.correct);
    const created = await prisma.question.create({
      data: {
        section: q.section,
        subtype: q.subtype,
        difficulty: q.difficulty,
        prompt: q.prompt,
        explanation: q.explanation,
        correctChoiceId: "placeholder",
        choices: {
          create: q.choices.map(c => ({
            label: c.label,
            text: c.correct ? `${c.text} (Correct)` : c.text,
          })),
        },
      },
      include: { choices: true },
    });
    const correctChoice = created.choices[correctIndex];
    await prisma.question.update({
      where: { id: created.id },
      data: { correctChoiceId: correctChoice.id },
    });
  }

  const counts = questions.reduce<Record<string,number>>((acc, q) => {
    const key = `${q.section}·${q.subtype}`;
    acc[key] = (acc[key] ?? 0) + 1;
    return acc;
  }, {});
  console.log("\nBreakdown:");
  Object.entries(counts).sort().forEach(([k,v]) => console.log(`  ${k}: ${v}`));
  console.log(`\nTotal: ${questions.length} questions seeded.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
